### ISSUE TITLE
IntervalArray should extend concrete type

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/utils#98]
Calling concreteIntervalArray.insert() or concreteIntervalArray.filter() will return IntervalArray(). For IntervalArray replace() function to work correctly with ConcreteIntervalArray, replace() should not return IntervalArray[K,T], but the derived type.
If there is a way around this, let me know. Otherwise I can submit a PR for this fix.

**Comment by fnothaft** [comment]
We can make those methods return the imp'l type, but you shouldn't need that. What breaks/what error are you getting now? If you are getting a compile error, you may need to specify the val type as the trait `IntervalArray[K, T]`, otherwise type inference may infer the type to be the concrete implementation type `ConcreteIntervalArray[K, T]`.

**Comment by akmorrow13** [comment]
Great, just setting to IntervalArray[] works. I will close this issue.
